/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/api/v1/auth/login': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['AuthController_login'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/health': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['HealthController_check'];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/form-types': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FormTypesController_findAllFormTypes'];
    put?: never;
    post: operations['FormTypesController_createFormType'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/form-types/{formTypeId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get: operations['FormTypesController_getFormType'];
    put?: never;
    post?: never;
    delete: operations['FormTypesController_deleteFormType'];
    options?: never;
    head?: never;
    patch: operations['FormTypesController_updateFormType'];
    trace?: never;
  };
  '/api/v1/form-types/{formTypeId}/fields': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post: operations['FormTypesController_addField'];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/form-types/{formTypeId}/fields/order': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put: operations['FormTypesController_reorderFields'];
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  '/api/v1/form-types/{formTypeId}/fields/{fieldId}': {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    post?: never;
    delete: operations['FormTypesController_removeField'];
    options?: never;
    head?: never;
    patch: operations['FormTypesController_updateField'];
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    LoginDto: {
      /** @description The shared application password. */
      password: string;
    };
    LoginResponseDto: {
      /** @description Signed JWT session token. */
      accessToken: string;
    };
    CreateFormTypeDto: {
      /** @description Name of the form type. */
      name: string;
      /** @description Description of the form type. */
      description?: string;
    };
    FormFieldResponseDto: {
      id: string;
      formTypeId: string;
      label: string;
      /** @enum {string} */
      fieldType:
        | 'text'
        | 'textarea'
        | 'number'
        | 'boolean'
        | 'select'
        | 'multi_select'
        | 'date';
      isRequired: boolean;
      options?: string[] | null;
      orderIndex: number;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
    };
    FormTypeResponseDto: {
      id: string;
      name: string;
      description?: string | null;
      /** Format: date-time */
      createdAt: string;
      /** Format: date-time */
      updatedAt: string;
      fields: components['schemas']['FormFieldResponseDto'][];
    };
    UpdateFormTypeDto: {
      /** @description Name of the form type. */
      name?: string;
      /** @description Description of the form type. */
      description?: string;
    };
    CreateFormFieldDto: {
      /** @description Label shown for the field. */
      label: string;
      /**
       * @description Data type of the field.
       * @enum {string}
       */
      fieldType:
        | 'text'
        | 'textarea'
        | 'number'
        | 'boolean'
        | 'select'
        | 'multi_select'
        | 'date';
      /**
       * @description Whether the field must be filled in to complete a response.
       * @default false
       */
      isRequired: boolean;
      /** @description Available options. Required (non-empty) for `select`/`multi_select`; must be omitted otherwise. */
      options?: string[];
    };
    ReorderFieldsDto: {
      /** @description Ordered list of field ids: must contain exactly the form type's current field ids, in the desired order. */
      fieldIds: string[];
    };
    UpdateFormFieldDto: {
      /** @description Label shown for the field. */
      label?: string;
      /**
       * @description Data type of the field.
       * @enum {string}
       */
      fieldType?:
        | 'text'
        | 'textarea'
        | 'number'
        | 'boolean'
        | 'select'
        | 'multi_select'
        | 'date';
      /** @description Whether the field must be filled in to complete a response. */
      isRequired?: boolean;
      /** @description Available options. Required (non-empty) for `select`/`multi_select`; must be null/omitted otherwise. */
      options?: string[] | null;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  AuthController_login: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['LoginDto'];
      };
    };
    responses: {
      /** @description Password matched the shared app password; returns a session token. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['LoginResponseDto'];
        };
      };
      /** @description Password didn't match the shared app password. */
      401: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  HealthController_check: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The API is up and reachable. */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_findAllFormTypes: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormTypeResponseDto'][];
        };
      };
    };
  };
  FormTypesController_createFormType: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFormTypeDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormTypeResponseDto'];
        };
      };
    };
  };
  FormTypesController_getFormType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormTypeResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_deleteFormType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_updateFormType: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFormTypeDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormTypeResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_addField: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['CreateFormFieldDto'];
      };
    };
    responses: {
      201: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormFieldResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_reorderFields: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['ReorderFieldsDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormTypeResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_removeField: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
        fieldId: string;
      };
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      204: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
  FormTypesController_updateField: {
    parameters: {
      query?: never;
      header?: never;
      path: {
        formTypeId: string;
        fieldId: string;
      };
      cookie?: never;
    };
    requestBody: {
      content: {
        'application/json': components['schemas']['UpdateFormFieldDto'];
      };
    };
    responses: {
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          'application/json': components['schemas']['FormFieldResponseDto'];
        };
      };
      404: {
        headers: {
          [name: string]: unknown;
        };
        content?: never;
      };
    };
  };
}
